%!assert(runMWE(@mweMIMO_DMC) < 19)
%!assert(runMWE(@mweMIMO_GPC) < 18)
%!assert(runMWE(@mweMIMO_MPCNO) < 4)
%!assert(runMWE(@mweMIMO_MPCS) < 18)
%!assert(runMWE(@mweSISO_DMC_Disturbance) < 18)
%!assert(runMWE(@mweSISO_DMC) < 54)
%!assert(runMWE(@mweSISO_GPC) < 32)
%!assert(runMWE(@mweSISO_MPCS) < 32)
